### ISSUE TITLE
WISH: ctop - disable dashlines to save vertical space

### ISSUE THREAD

**Issue by HenrikBengtsson** [molgenis/cluster-utils#34]
# Issue

When using `ctop`, each node consumes at least two lines in the grid view, because of the dashlines (`---------------`) separating each node.  If you've got lots of nodes, you end up running out of vertical space.

# Wish

Add an option to not print those dashlines, e.g.
```sh
$ ctop -H
```

That could effectively reduce the number of lines used by the grid view to as much as 50%.

The option could disable the two calls to `_PrintDashLine()`;

https://github.com/molgenis/cluster-utils/blob/a9a1f412a0beb3d78fc1d3ce9dc8055912307ce7/bin/ctop-slurm#L1138

https://github.com/molgenis/cluster-utils/blob/a9a1f412a0beb3d78fc1d3ce9dc8055912307ce7/bin/ctop-slurm#L1302

**Comment by pneerincx** [comment]
Implemented in https://github.com/molgenis/cluster-utils/releases/tag/v22.10.2

**Comment by HenrikBengtsson** [comment]
Beautiful. Thank you!
